### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by 1363480914** [isboyjc/isle-editor#1]
用的是npm install @isle-editor/core @isle-editor/vue3

项目中导入依赖import { Editor, IsleEditor } from '@isle-editor/vue3';

之后npm run dev，所有的icons都报错，报错入下
Could not resolve "~icons/tabler/row-remove"

node_modules/@isle-editor/vue3/dist/index.js:54:22:

**Comment by isboyjc** [comment]
感谢提醒，前几天换了个图标库，引入有点问题，稍后会更新

**Comment by isboyjc** [comment]
另外目前不建议您在生产环境中使用 isle-editor，因为没有正式发版，迭代有些频繁

**Comment by 1363480914** [comment]
好的，感谢提醒；
